# Name of website
title: Biodegradable Seed Spreading Robot 

# Your name to show in the footer
author: Team 1

# Website Description
description: Foldable Robotics

# Website theme
theme: jekyll-theme-slate